mutation CreateUser($fullName: String!, $email: String!, $role: String!) @auth(level: PUBLIC) {
  user_insert(data: {
    fullName: $fullName,
    email: $email,
    role: $role
  })
}

mutation CreateGroup($name: String!, $type: String!, $adminUserId: UUID!) @auth(level: USER) {
  group_insert(data: {
    name: $name,
    type: $type,
    creationDate: "2023-10-27T10:00:00Z",
    adminUserId: $adminUserId
  })
}

query ListGroups @auth(level: USER) {
  groups(limit: 20) {
    id
    name
    type
    adminUser {
      fullName
      email
    }
  }
}

mutation JoinGroup($userId: UUID!, $groupId: UUID!) @auth(level: USER) {
  membership_insert(data: {
    userId: $userId,
    groupId: $groupId,
    joinDate: "2023-10-27T12:00:00Z",
    status: "active"
  })
}